### ISSUE TITLE
Errors compiling on Ubuntu 18.04 with SFML 2.5.1

### ISSUE THREAD

**Issue by SnowySailor** [HackerPoet/MarbleMarcher#6]
I installed SFML once from source and once using the precompiled libraries for Linux here: https://www.sfml-dev.org/download/sfml/2.5.1/ (also tried 2.5.0).

Everything up until `cmake --build build` worked fine. Once I ran that command, however, I got the following error:

```
[ 87%] Linking CXX executable MarbleMarcher
CMakeFiles/MarbleMarcher.dir/src/Main.cpp.o: In function `main':
Main.cpp:(.text+0xa53): undefined reference to `sf::RenderTexture::create(unsigned int, unsigned int, sf::ContextSettings const&)'
Main.cpp:(.text+0xa8f): undefined reference to `sf::RenderWindow::setActive(bool)'
src/libMarbleMarcherSources.a(Overlays.cpp.o): In function `Overlays::UpdateMenu(float, float)':
Overlays.cpp:(.text+0x913): undefined reference to `sf::Text::setLineSpacing(float)'
Overlays.cpp:(.text+0x92d): undefined reference to `sf::Text::setLineSpacing(float)'
src/libMarbleMarcherSources.a(Overlays.cpp.o): In function `Overlays::UpdateControls(float, float)':
Overlays.cpp:(.text+0xa5c): undefined reference to `sf::Text::setLineSpacing(float)'
Overlays.cpp:(.text+0xa76): undefined reference to `sf::Text::setLineSpacing(float)'
src/libMarbleMarcherSources.a(Overlays.cpp.o): In function `Overlays::DrawCredits(sf::RenderWindow&)':
Overlays.cpp:(.text+0x1a92): undefined reference to `sf::Text::setLineSpacing(float)'
src/libMarbleMarcherSources.a(Overlays.cpp.o): In function `Overlays::MakeText(char const*, float, float, float, sf::Color const&, sf::Text&, bool)':
Overlays.cpp:(.text+0x1e2f): undefined reference to `sf::Text::setLetterSpacing(float)'
src/libMarbleMarcherSources.a(SelectRes.cpp.o): In function `SelectRes::MakeText(char const*, float, float, int, bool, bool) const':
SelectRes.cpp:(.text+0x72a): undefined reference to `sf::Text::setLetterSpacing(float)'
collect2: error: ld returned 1 exit status
CMakeFiles/MarbleMarcher.dir/build.make:95: recipe for target 'MarbleMarcher' failed
make[2]: *** [MarbleMarcher] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MarbleMarcher.dir/all' failed
make[1]: *** [CMakeFiles/MarbleMarcher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Seems to be something to do with SFML, but I'm not sure exactly what. I thought it was something to do with the specific library I installed, but I got the same error when using the precompiled one. Any ideas?

Thanks

**Comment by HackerPoet** [comment]
SFML supports 2 types of libraries, static and dynamic, and this error can occur if you mix them.  I use static libraries in my builds with the `SFML_STATIC` preprocessor flag, not sure if the same is true on Linux...

**Comment by eacousineau** [comment]
BTW I was able to get this to build on Ubuntu 18.04 w/ SFML 2.5.1 (but building from source), and submitted this PR: #39 

Not sure if it'll resolve the static vs. shared linking, but it at least gets things going.

**Comment by Modanung** [comment]
@tuxutku Could you link to the deb, please?

**Comment by tuxutku** [comment]
off course @Modanung 
https://pkgs.org/download/libsfml-audio2.5
https://pkgs.org/download/libsfml-system2.5
https://pkgs.org/download/libsfml-window2.5
https://pkgs.org/download/libsfml-network2.5
https://pkgs.org/download/libsfml-graphics2.5
https://pkgs.org/download/libsfml-dev
WARNING: don't forget to download for the right distro
WARNING: you have to install all

**Comment by gr4viton** [comment]
As i was not sure and it took me some time to get it working i am gonna post a summary.
## How to build and run `MarbleMarcher` on Ubuntu 18.04
- install `libsfml-dev` version 2.5.0
    - 18.04 has dependency package `libsfml-dev` version 2.4.1, `MarbleMarcher` needs 2.5.0
    - download individual `libsfml` packages version 2.5.0 for your distribution
        - select your distro (eg Ubuntu 18.10) and platform (amd64)
        - https://pkgs.org/download/libsfml-audio2.5
        - https://pkgs.org/download/libsfml-system2.5
        - https://pkgs.org/download/libsfml-window2.5
        - https://pkgs.org/download/libsfml-network2.5
        - https://pkgs.org/download/libsfml-graphics2.5
        - https://pkgs.org/download/libsfml-dev
    - install them all
        - if in one directory run `sudo apt install ./*`
- install other dependencies (not sure if this is all you need)
    - `sudo apt install libeigen3-dev git cmake make`
- get `MarbleMarcher` source
```
cd ~
git clone https://github.com/HackerPoet/MarbleMarcher
cd MarbleMarcher
```
- edit `CmakeLists.txt`
  - delete `SFML_STATIC` word (cause we are using the installed deb packages)
- build the `MarbleMarcher`
```
( set -eux;
  mkdir build && cd build
  cmake ..
  make -j
  cp MarbleMarcher ..
)
```
- run the `MarbleMarcher` via `./MarbleMarcher`
